/*
 * This file is generated by jOOQ.
*/
package com.st.db;


import com.st.db.tables.Messages;
import com.st.db.tables.Order;
import com.st.db.tables.OrderDetail;
import com.st.db.tables.Posts;
import com.st.db.tables.Product;
import com.st.db.tables.ProductsCategory;
import com.st.db.tables.ProductsMark;
import com.st.db.tables.Telegrammessages;
import com.st.db.tables.Users;
import com.st.db.tables.records.MessagesRecord;
import com.st.db.tables.records.OrderDetailRecord;
import com.st.db.tables.records.OrderRecord;
import com.st.db.tables.records.PostsRecord;
import com.st.db.tables.records.ProductRecord;
import com.st.db.tables.records.ProductsCategoryRecord;
import com.st.db.tables.records.ProductsMarkRecord;
import com.st.db.tables.records.TelegrammessagesRecord;
import com.st.db.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = UniqueKeys0.MESSAGES_PKEY;
    public static final UniqueKey<OrderRecord> ORDER_PKEY = UniqueKeys0.ORDER_PKEY;
    public static final UniqueKey<OrderDetailRecord> ORDER_DETAIL_PKEY = UniqueKeys0.ORDER_DETAIL_PKEY;
    public static final UniqueKey<PostsRecord> POSTS_PKEY = UniqueKeys0.POSTS_PKEY;
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = UniqueKeys0.PRODUCT_PKEY;
    public static final UniqueKey<ProductsCategoryRecord> PRODUCTS_CATEGORY_PKEY = UniqueKeys0.PRODUCTS_CATEGORY_PKEY;
    public static final UniqueKey<ProductsCategoryRecord> PRODUCTS_CATEGORY_NAME_KEY = UniqueKeys0.PRODUCTS_CATEGORY_NAME_KEY;
    public static final UniqueKey<ProductsMarkRecord> PRODUCTS_MARK_PKEY = UniqueKeys0.PRODUCTS_MARK_PKEY;
    public static final UniqueKey<ProductsMarkRecord> PRODUCTS_MARK_NAME_KEY = UniqueKeys0.PRODUCTS_MARK_NAME_KEY;
    public static final UniqueKey<TelegrammessagesRecord> TELEGRAMMESSAGES_PKEY = UniqueKeys0.TELEGRAMMESSAGES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderRecord, UsersRecord> ORDER__FK_ORDERS_USERID = ForeignKeys0.ORDER__FK_ORDERS_USERID;
    public static final ForeignKey<OrderDetailRecord, OrderRecord> ORDER_DETAIL__FK_ORDERS_ORDERID = ForeignKeys0.ORDER_DETAIL__FK_ORDERS_ORDERID;
    public static final ForeignKey<OrderDetailRecord, ProductRecord> ORDER_DETAIL__FK_PRODUCT_PRODUCTID = ForeignKeys0.ORDER_DETAIL__FK_PRODUCT_PRODUCTID;
    public static final ForeignKey<ProductRecord, ProductsMarkRecord> PRODUCT__FK_PRODUCTS_MARK = ForeignKeys0.PRODUCT__FK_PRODUCTS_MARK;
    public static final ForeignKey<ProductRecord, ProductsCategoryRecord> PRODUCT__FK_PRODUCTS_CATEGORY = ForeignKeys0.PRODUCT__FK_PRODUCTS_CATEGORY;
    public static final ForeignKey<TelegrammessagesRecord, PostsRecord> TELEGRAMMESSAGES__FK_TELEGRAMMESSAGES_POSTS = ForeignKeys0.TELEGRAMMESSAGES__FK_TELEGRAMMESSAGES_POSTS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = createUniqueKey(Messages.MESSAGES, "messages_pkey", Messages.MESSAGES.ID);
        public static final UniqueKey<OrderRecord> ORDER_PKEY = createUniqueKey(Order.ORDER, "order_pkey", Order.ORDER.ID);
        public static final UniqueKey<OrderDetailRecord> ORDER_DETAIL_PKEY = createUniqueKey(OrderDetail.ORDER_DETAIL, "order_detail_pkey", OrderDetail.ORDER_DETAIL.ORDERID);
        public static final UniqueKey<PostsRecord> POSTS_PKEY = createUniqueKey(Posts.POSTS, "posts_pkey", Posts.POSTS.ID);
        public static final UniqueKey<ProductRecord> PRODUCT_PKEY = createUniqueKey(Product.PRODUCT, "product_pkey", Product.PRODUCT.ID);
        public static final UniqueKey<ProductsCategoryRecord> PRODUCTS_CATEGORY_PKEY = createUniqueKey(ProductsCategory.PRODUCTS_CATEGORY, "products_category_pkey", ProductsCategory.PRODUCTS_CATEGORY.ID);
        public static final UniqueKey<ProductsCategoryRecord> PRODUCTS_CATEGORY_NAME_KEY = createUniqueKey(ProductsCategory.PRODUCTS_CATEGORY, "products_category_name_key", ProductsCategory.PRODUCTS_CATEGORY.NAME);
        public static final UniqueKey<ProductsMarkRecord> PRODUCTS_MARK_PKEY = createUniqueKey(ProductsMark.PRODUCTS_MARK, "products_mark_pkey", ProductsMark.PRODUCTS_MARK.ID);
        public static final UniqueKey<ProductsMarkRecord> PRODUCTS_MARK_NAME_KEY = createUniqueKey(ProductsMark.PRODUCTS_MARK, "products_mark_name_key", ProductsMark.PRODUCTS_MARK.NAME);
        public static final UniqueKey<TelegrammessagesRecord> TELEGRAMMESSAGES_PKEY = createUniqueKey(Telegrammessages.TELEGRAMMESSAGES, "telegrammessages_pkey", Telegrammessages.TELEGRAMMESSAGES.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<OrderRecord, UsersRecord> ORDER__FK_ORDERS_USERID = createForeignKey(com.st.db.Keys.USERS_PKEY, Order.ORDER, "order__fk_orders_userId", Order.ORDER.USERID);
        public static final ForeignKey<OrderDetailRecord, OrderRecord> ORDER_DETAIL__FK_ORDERS_ORDERID = createForeignKey(com.st.db.Keys.ORDER_PKEY, OrderDetail.ORDER_DETAIL, "order_detail__fk_orders_orderId", OrderDetail.ORDER_DETAIL.ORDERID);
        public static final ForeignKey<OrderDetailRecord, ProductRecord> ORDER_DETAIL__FK_PRODUCT_PRODUCTID = createForeignKey(com.st.db.Keys.PRODUCT_PKEY, OrderDetail.ORDER_DETAIL, "order_detail__fk_product_productId", OrderDetail.ORDER_DETAIL.PRODUCTID);
        public static final ForeignKey<ProductRecord, ProductsMarkRecord> PRODUCT__FK_PRODUCTS_MARK = createForeignKey(com.st.db.Keys.PRODUCTS_MARK_NAME_KEY, Product.PRODUCT, "product__fk_products_mark", Product.PRODUCT.MARK);
        public static final ForeignKey<ProductRecord, ProductsCategoryRecord> PRODUCT__FK_PRODUCTS_CATEGORY = createForeignKey(com.st.db.Keys.PRODUCTS_CATEGORY_NAME_KEY, Product.PRODUCT, "product__fk_products_category", Product.PRODUCT.CATEGORY);
        public static final ForeignKey<TelegrammessagesRecord, PostsRecord> TELEGRAMMESSAGES__FK_TELEGRAMMESSAGES_POSTS = createForeignKey(com.st.db.Keys.POSTS_PKEY, Telegrammessages.TELEGRAMMESSAGES, "telegramMessages__fk_telegramMessages_posts", Telegrammessages.TELEGRAMMESSAGES.ID_POST);
    }
}
