/*
 * This file is generated by jOOQ.
*/
package com.st.db;


import com.st.db.tables.Messages;
import com.st.db.tables.Order;
import com.st.db.tables.OrderDetail;
import com.st.db.tables.Posts;
import com.st.db.tables.Product;
import com.st.db.tables.ProductsCategory;
import com.st.db.tables.ProductsMark;
import com.st.db.tables.Telegrammessages;
import com.st.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = com.st.db.tables.Messages.MESSAGES;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = com.st.db.tables.Order.ORDER;

    /**
     * The table <code>public.order_detail</code>.
     */
    public static final OrderDetail ORDER_DETAIL = com.st.db.tables.OrderDetail.ORDER_DETAIL;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = com.st.db.tables.Posts.POSTS;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = com.st.db.tables.Product.PRODUCT;

    /**
     * The table <code>public.products_category</code>.
     */
    public static final ProductsCategory PRODUCTS_CATEGORY = com.st.db.tables.ProductsCategory.PRODUCTS_CATEGORY;

    /**
     * The table <code>public.products_mark</code>.
     */
    public static final ProductsMark PRODUCTS_MARK = com.st.db.tables.ProductsMark.PRODUCTS_MARK;

    /**
     * The table <code>public.telegramMessages</code>.
     */
    public static final Telegrammessages TELEGRAMMESSAGES = com.st.db.tables.Telegrammessages.TELEGRAMMESSAGES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.st.db.tables.Users.USERS;
}
